<?php \App\Core\Includes\Session::unset('id'); ?>

<div id="form-div">

<div class="errors">
    <?php if (isset($errors)): ?>
        <?php foreach($errors as $error): ?>
            <label><?php echo $error; ?></label>
        <?php endforeach; ?>
    <?php endif; ?>
</div>

    <form action="/login" id="form" method="post">

        <div class="form-field">
            <label for="username">Username</label>
            <input type="text" name="username" id="username" placeholder="username">
        </div>

        <div class="form-field">
            <label for="password">Password</label>
            <input type="password" name="password" placeholder="********">
        </div>

        <div class="form-field">
            <label for="remember">
                <input type="checkbox" name="remember" id="remember">
                Save me
            </label>
        </div>

        <div class="form-field">
            <label for=""></label>
            <input type="submit" value="Login">
        </div>

        <span style="float: right">Not a member? <a href="/register">Register</a></span>
    </form>
</div>
