


<div class="gallery-wrap">

    <div class="my-gallery">
        <p>My galleries</p>
    </div>

    <?php foreach ($galleries as $gallery): ?>
    <div class="gallery-card" id="gallery-card-<?php echo $gallery->id;?>">
        <div class="delete-gallery">
            <form class="delete-gallery-form" id="delete-gallery-<?php echo $gallery->id;?>" action="/galleries/<?php echo $gallery->id;?>" method="post">
                <input type="submit" value="X">
            </form>
        </div>
        <a href="/galleries/<?php echo $gallery->id;?>/show">
            <img src="/<?php echo $gallery->image;?>" alt="">
        </a>
        <div class="gallery-body">
            <h3><?php echo $gallery->title;?></h3>
            <p><?php echo ! empty($gallery->description) ? $gallery->description : 'No description';?></p>
        </div>
        <!-- /.gallery-body -->
    </div>
    <?php endforeach; ?>
    <!-- /.gallery-card -->
</div>
<!-- /.gallery-wrap -->