<div>
    <form action="/register" method="post">
        <input type="text" name="first_name" placeholder="fname">

        <input type="text" name="last_name" placeholder="lname">
        <input type="text" name="username" placeholder="uname">
        <input type="text" name="email" placeholder="email">
        <input type="password" name="password" placeholder="pw">
        <input type="password" name="password_again" placeholder="pw, again">

        <input type="submit" value="Register">
    </form>
</div>