<div class="gallery-wrap">

    <div class="gallery-info">
        <p><?php echo $gallery->title; ?></p>
        <p><i><?php echo ! empty($gallery->description) ? $gallery->description : 'No description';?></i></p>
    </div>

    <?php foreach ($images as $image): ?>
    <div class="gallery-card" id="image-card-<?php echo $image->id;?>">

        <?php if($user->id === $gallery->user_id): ?>
            <div class="delete-gallery">
                <form class="delete-image-form" id="delete-image-<?php echo $image->id;?>" action="/images/<?php echo $image->id;?>" method="post">
                    <input type="submit" value="X">
                </form>
            </div>
        <?php endif; ?>

        <a href="#">
            <img src="/<?php echo $image->image;?>" alt="">
        </a>
        <div class="gallery-body">
            <h3 id="image-title-<?php echo $image->id;?>"><?php echo $image->title;?></h3>
        </div>
        <!-- /.gallery-body -->
    </div>
    <?php endforeach; ?>
    <!-- /.gallery-card -->
</div>
<!-- /.gallery-wrap -->