<div class="gallery-wrap">

    <div class="gallery-info">
        <p><?php echo $gallery->title; ?></p>
        <p><i><?php echo ! empty($gallery->description) ? $gallery->description : 'No description';?></i></p>
    </div>

    <?php foreach ($images as $image): ?>
    <div class="gallery-card" id="gallery-card-<?php echo $image->id;?>">
        <div class="delete-gallery">
            <form class="delete-gallery-form" id="delete-gallery-<?php echo $image->id;?>" action="/galleries/<?php echo $image->id;?>" method="post">
                <input type="submit" value="X">
            </form>
        </div>
        <a href="#">
            <img src="/<?php echo $image->image;?>" alt="">
        </a>
        <div class="gallery-body">
            <h3><?php echo $image->title;?></h3>
        </div>
        <!-- /.gallery-body -->
    </div>
    <?php endforeach; ?>
    <!-- /.gallery-card -->
</div>
<!-- /.gallery-wrap -->