<div class="profile">
    <h1>Profile details</h1>

    <div class="profile__field">
        <span>Full name:</span> <?php echo $user->first_name . " " . $user->last_name; ?>
    </div>

    <div class="profile__field">
        <span>Email address:</span> <?php echo $user->email; ?>
    </div>

    <div class="profile__field">
        <span>Username:</span> <?php echo $user->username; ?>
    </div>

    <div class="profile__field" id="profile-uploads-info">
       <i></i>
    </div>

    <div class="profile__actions">
        <a href="#" id="change-password" onclick="toggle()">Change password</a>

        <form action="/profile/<?php echo $user->id; ?>/destroy" id="delete-account" method="post">
            <input type="submit" value="Delete account">
        </form>
    </div>


    <div class="form-popup" style="<?php if (isset($errors) || isset($success)) echo "display: block" ?>" id="change-password-popup">
        <form action="/profile" class="change-password-form" method="post">

            <input
                    type="password"
                    style="<?php if (isset($alerts['current_password'])) echo "border: 2px red solid" ?>"
                    placeholder="Current password"
                    name="current_password">

            <input
                    type="password"
                    style="<?php if (isset($alerts['new_password'])) echo "border: 2px red solid" ?>"
                    placeholder="New password"
                    name="new_password">

            <input
                    type="password"
                    style="<?php if (isset($alerts['new_password_again'])) echo "border: 2px red solid" ?>"
                    placeholder="New password, again"
                    name="new_password_again">

            <input type="submit" value="Change">
        </form>

        <?php if (isset($success)): ?>
            <div class="password-success">
                    <label><?php echo $success; ?></label>
            </div>
        <?php endif; ?>

        <?php if (isset($errors)): ?>
            <div class="password-errors">
                    <?php foreach($errors as $error): ?>
                        <label><?php echo $error; ?></label>
                    <?php endforeach; ?>
            </div>
        <?php endif; ?>
    </div>

</div>



<script type="application/javascript">
    function toggle(){
        var form = document.getElementById('change-password-popup')

        if (form.style.display === 'block'){
            form.style.display = 'none'
        }else{
            form.style.display = 'block'
        }
    }
</script>