<div id="form-div">

    <div class="errors">
        <?php if (isset($errors)): ?>
            <?php foreach($errors as $error): ?>
                <label><?php echo $error; ?></label>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>

    <form action="/gallery/store" id="form" method="post" enctype="multipart/form-data">

        <div class="form-field">
            <label for="title">Title</label>
            <input type="text" name="title" id="title" placeholder="Enter a new name">
        </div>

        <div class="form-field">
            <label for="description">Description</label>
            <textarea
                name="description"
                id="description"
                cols="30"
            ></textarea>
        </div>

        <div class="form-field">
            <label for="image">Image</label>
            <input type="file" name="images" id="image">
        </div>

        <div class="form-field">
            <label for=""></label>
            <input type="submit" value="Create">
        </div>
    </form>
</div>