<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?php echo $documentName; ?></title>
</head>
<body>

<nav id="nav">
    <?php require '_partials/nav.phtml'; ?>
</nav>

<?php require $file; ?>

</body>
</html>