<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/css/app.css">

    <title><?php echo $documentName; ?></title>
</head>
<body>

<?php if($documentName !== 'Register' && $documentName !== 'Login'): ?>
<nav id="nav">
    <?php require '_partials/nav.phtml'; ?>
</nav>
<?php endif; ?>

<?php require $file; ?>

<script src="https://code.jquery.com/jquery-latest.min.js"></script>
<script src="/js/delete-gallery.js"></script>
<script src="/js/delete-image.js"></script>

<script type="application/javascript">
    let g = "<?php echo count($user->galleries()); ?>"
    let i = "<?php echo count($user->images()); ?>"
</script>
<script src="/js/pluralizer.js"></script>

</body>
</html>