<a href="/home"><p>GALLERY</p></a>
<ul>
    <li></li>
    <li>
        <a href="#">Actions*</a>
        <ul>
            <li><a href="/galleries/create">Make Gallery</a></li>
            <li><a href="">Upload Image</a></li>
        </ul>
    </li>

    <ul>
        <li>
            <a href="#"><?php if(isset($user)): echo $user->first_name; endif; ?>*</a>
            <ul>
                <li><a href="">Options</a></li>
                <li><a href="/out">Sign out</a></li>
            </ul>
        </li>
    </ul>
</ul>